---
- name: Install dependency packages for elm development environment
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - libncurses5-dev
  sudo: yes

- name: Update cabal package manager
  command: cabal update creates=.cabal

- name: Install base packages for elm development environment
  command: cabal install elm elm-server elm-repl elm-get creates=.cabal/bin/elm

- name: Add elm commands to path
  lineinfile:
    dest: .profile
    line: PATH="$PATH:$HOME/.cabal/bin"
    state: present