---
- name: Install base development packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - git

- name: Set git config file values
  template:
    src=.gitconfig
    dest=/home/{{ docker_dev_user }}
    owner={{ docker_dev_user }}
    group={{ docker_dev_user }}

