---
- name: Create laravel project
  command: composer --no-interaction create-project laravel/laravel php-laravel-project/ --prefer-dist
  args:
    creates: php-laravel-project/composer.lock

- name: Add install script
  copy:
    src=init.sh
    dest=~/php-laravel-project
    mode=0700
