---
- name: Stop and remove docker container for development environment
  docker:
    name: "{{ docker_dev_container }}" # use named container for idempotency
    image: phusion/baseimage
    state: absent
