---
- name: Start docker container for development environment
  docker:
    name: docker-dev-env     # use named container for idempotency
    image: phusion/baseimage
    privileged: True
    state: running
    command: "/sbin/my_init --enable-insecure-key"

- name: Add docker IPs to host group
  add_host: hostname={{ item.NetworkSettings.IPAddress }} groupname=docker-dev
  with_items: docker_containers
