---
- name: Start docker container for development environment
  docker:
    name: "{{ docker_dev_container }}" # use named container for idempotency
    image: phusion/baseimage
    privileged: True
    state: running
    command: "/sbin/my_init --enable-insecure-key"

- name: Add docker IPs to host group
  add_host: hostname={{ item.NetworkSettings.IPAddress }} groupname=docker-dev
  with_items: docker_containers

- name: Install phusion/baseimage insecure private key on host
  command: curl -o /home/vagrant/.ssh/phusion_baseimage_insecure_key -fSL https://github.com/phusion/baseimage-docker/raw/master/image/insecure_key
    creates=/home/vagrant/.ssh/phusion_baseimage_insecure_key

- name: Set 0600 permissions on phusion/baseimage private key
  file:
    path=/home/vagrant/.ssh/phusion_baseimage_insecure_key
    mode=0600
    state=file

# TODO: assess better ways to add these lines
- name: Add container phusion/baseimage private key placeholder to ssh config
  lineinfile:
    dest: /home/vagrant/.ssh/config
    line: "{{ item.line }}"
    state: present
    create: yes
    backup: yes
  with_items:
    - line: "# docker-dev-env --generated block--"

- name: Add container phusion/baseimage private key to ssh config
  lineinfile:
    dest: /home/vagrant/.ssh/config
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - insertafter: 
      line: "# docker-dev-env --generated block--"
    - insertafter: "# docker-dev-env --generated block--"
      line: "Host {{ docker_containers[0].NetworkSettings.IPAddress }}"
    - insertafter: "Host {{ docker_containers[0].NetworkSettings.IPAddress }}"
      line: "IdentityFile ~/.ssh/phusion_baseimage_insecure_key"

- name: Wait until we can ssh in to the new container(s)
  command: ssh -oStrictHostKeyChecking=no root@{{ item.NetworkSettings.IPAddress }} /bin/echo UP
  register: connections
  until: connections.stdout == "UP"
  retries: 10
  delay: 1
  with_items: docker_containers
