---
- name: Install base packages for ruby development environment
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - ruby1.9.1

- name: Install required gems
  gem: name={{ item }} state=present
  with_items: ruby_gems
  when: ruby_gems
