---
- name: Transfer sinatra project files to container
  copy: src=ruby193-sinatra-project dest=.

- name: Install sinatra project dependencies
  command: bundle install --path vendor/bundle
  args:
    chdir: ruby193-sinatra-project
    creates: Gemfile.lock

