---
- name: Install yeoman packages
  npm: name=yo global=yes state=present

- name: Install yeoman generators
  npm: name={{ item }} global=yes state=present
  with_items: yeoman_generators
  when: yeoman_generators
